api:
  build: api
  ports:
    - "3000:3000"
  links:
    - rethinkdb

rethinkdb:
  build: rethinkdb
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  volumes:
    - ./rethinkdb/data:/data
